[tool.poetry]
name = "abstractoperatorsinterns"
version = "0.1.0"
description = ""
authors = ["vvijay874 <vvijay@imsa.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
<<<<<<< Updated upstream
python = "^3.12"
=======
python = "^3.10"
>>>>>>> Stashed changes


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
